# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sogapp', '0002_artistinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfo',
            name='artist_photo',
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='artist_photo1_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='artist_photo2_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='artist_photo3_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
